services:
  - type: web
    name: opt-pal
    env: python
    plan: free
    buildCommand: uv sync --frozen && uv run python import_data_into_SQL.py && uv cache prune --ci
    startCommand: uv run gunicorn app:app
    autoDeploy: true
